### ISSUE TITLE
Can't install from PyPi

### ISSUE THREAD

**Issue by melbic** [ramusus/django-facebook-api#2]
```Collecting pyfacegraph>=0.0.36 (from django-facebook-api)
  Could not find a version that satisfies the requirement pyfacegraph>=0.0.36 (from django-facebook-api) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4)
  No matching distribution found for pyfacegraph>=0.0.36 (from django-facebook-api)```

**Comment by ramusus** [comment]
There is open issue https://github.com/colinhowe/pyFaceGraph/issues/13 for this.
You can solve problem by install right version of pyfacegraph manually:
```
-e git+https://github.com/iplatform/pyFaceGraph#egg=pyFaceGraph
```

**Comment by ramusus** [comment]
Just commit new version without pyfacegraph dependancy, but with https://github.com/pythonforfacebook/facebook-sdk. But the same situation with versions. Required version 1.0.0-alpha. Try install from repo
```
-e git+https://github.com/iplatform/pyFaceGraph#egg=pyFaceGraph
```
